POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1ZmZ0YWNvIiwiaWQiOiI2NGYxMGFhZmQxYjEwYjUyYmYwZDZhMzQiLCJpYXQiOjE2OTM1OTMxNDcsImV4cCI6MTY5MzU5Njc0N30.ZCTcOhgYiOiULdiY-jMBjG1GdnuOZZuP30u3B3nD4-g

{
    "title": "delete it",
    "author": "buff",
    "url": "smth.com",
    "likes": 3
}